/// Lyrics of the song.
List<String> getLyrics() {
  return [
    "Time is running out",
    "and I can't stop it ",
    "our love ain’t fire",
    "and I'm burning",
    "There is no light",
    "If you are far ",
    "from me ",
    "What can I do if I don't see you again?",
    "I’m not crazy, I'm just scared",
    "So baby please don't go",
    "cause I will miss you",
    "You, you shake my mind",
    "You, you burn my heart",
    "You, you stop time",
    "baby, baby I’ll standing here",
    "and I'll be waiting for you.",
    "You, you shake my mind",
    "You, you burn my heart",
    "You, you stop time",
    "baby, baby I’ll standing here",
    "and I'll be waiting for you.",
    "DROP",
    "Time is running out",
    "and I can't stop it ",
    "our love ain’t fire",
    "and I'm burning",
    "There is no light",
    "If you are far ",
    "from me ",
    "What can I do if I don't see you again?",
    "I’m not crazy, I'm just scared",
    "So baby please don't go",
    "cause I will miss you",
    "You, you shake my mind",
    "You, you burn my heart",
    "You, you stop time",
    "baby, baby I’ll standing here",
    "and I'll be waiting for you.",
    "You, you shake my mind",
    "You, you burn my heart",
    "You, you stop time",
    "baby, baby I’ll standing here",
    "and I'll be waiting for you.",
  ];
}
